import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { execFile } from "./utils.ts";

export const WKT_MARKETPLACE_NAME = "wkt";
export const PLUGIN_ASSET_DIRS = ["agents", "skills", "commands", "hooks"] as const;
export type PluginAssetDir = (typeof PLUGIN_ASSET_DIRS)[number];

export interface PluginEntry {
  name: string;
  source: string;
  description: string;
  version: string;
}

export interface MarketplaceManifest {
  name: string;
  owner: { name: string };
  metadata?: { description?: string; version?: string };
  plugins: PluginEntry[];
}

export interface PluginManifest {
  name: string;
  description: string;
  version: string;
  author: { name: string };
}

export function detectClaudeAssets(worktreePath: string): PluginAssetDir[] {
  const claudeDir = join(worktreePath, ".claude");
  if (!existsSync(claudeDir)) return [];
  return PLUGIN_ASSET_DIRS.filter((dir) => existsSync(join(claudeDir, dir)));
}

export function buildMarketplaceManifest(plugins: PluginEntry[]): MarketplaceManifest {
  return {
    name: WKT_MARKETPLACE_NAME,
    owner: { name: "wkt" },
    metadata: {
      description: "Local marketplace generated by wkt for the current workspace",
      version: "0.0.1",
    },
    plugins: [...plugins],
  };
}

export function buildPluginManifest(alias: string): PluginManifest {
  return {
    name: alias,
    description: `${alias} .claude assets (wkt worktree)`,
    version: "0.0.1",
    author: { name: "wkt" },
  };
}

export function addPluginToManifest(
  manifest: MarketplaceManifest,
  entry: PluginEntry,
): MarketplaceManifest {
  if (manifest.plugins.some((p) => p.name === entry.name)) {
    return { ...manifest, plugins: [...manifest.plugins] };
  }
  return { ...manifest, plugins: [...manifest.plugins, entry] };
}

export function removePluginFromManifest(
  manifest: MarketplaceManifest,
  name: string,
): MarketplaceManifest {
  return { ...manifest, plugins: manifest.plugins.filter((p) => p.name !== name) };
}

export function relativeAssetSymlinkTarget(alias: string, asset: PluginAssetDir): string {
  return `../../../../../${alias}/.claude/${asset}`;
}

function marketplaceDir(workspacePath: string): string {
  return join(workspacePath, ".claude", "marketplaces", WKT_MARKETPLACE_NAME);
}

function marketplaceManifestPath(workspacePath: string): string {
  return join(marketplaceDir(workspacePath), ".claude-plugin", "marketplace.json");
}

function pluginWrapperDir(workspacePath: string, alias: string): string {
  return join(marketplaceDir(workspacePath), "plugins", alias);
}

function readManifestOrEmpty(workspacePath: string): MarketplaceManifest {
  const path = marketplaceManifestPath(workspacePath);
  if (!existsSync(path)) return buildMarketplaceManifest([]);
  try {
    const raw = JSON.parse(readFileSync(path, "utf-8"));
    if (!raw || typeof raw !== "object" || !Array.isArray(raw.plugins)) {
      return buildMarketplaceManifest([]);
    }
    return raw as MarketplaceManifest;
  } catch {
    return buildMarketplaceManifest([]);
  }
}

function writeManifest(workspacePath: string, manifest: MarketplaceManifest): void {
  const path = marketplaceManifestPath(workspacePath);
  mkdirSync(join(marketplaceDir(workspacePath), ".claude-plugin"), { recursive: true });
  writeFileSync(path, JSON.stringify(manifest, null, 2) + "\n");
}

export function ensureClaudeCliAvailable(): void {
  try {
    execFile("claude", ["--version"]);
  } catch {
    throw new Error(
      "`claude` CLI not found in PATH. Install Claude Code or re-run with --link-claude=false.",
    );
  }
}

export interface BundleResult {
  pluginName: string;
  detectedAssets: PluginAssetDir[];
}

export function bundlePlugin(
  workspacePath: string,
  alias: string,
  worktreePath: string,
): BundleResult {
  const detectedAssets = detectClaudeAssets(worktreePath);
  const manifest = readManifestOrEmpty(workspacePath);
  const entry: PluginEntry = {
    name: alias,
    source: `./plugins/${alias}`,
    description: `${alias} .claude assets (wkt worktree)`,
    version: "0.0.1",
  };
  writeManifest(workspacePath, addPluginToManifest(manifest, entry));

  const wrapperDir = pluginWrapperDir(workspacePath, alias);
  mkdirSync(join(wrapperDir, ".claude-plugin"), { recursive: true });
  writeFileSync(
    join(wrapperDir, ".claude-plugin", "plugin.json"),
    JSON.stringify(buildPluginManifest(alias), null, 2) + "\n",
  );

  for (const asset of detectedAssets) {
    const linkPath = join(wrapperDir, asset);
    if (existsSync(linkPath)) continue;
    symlinkSync(relativeAssetSymlinkTarget(alias, asset), linkPath, "dir");
  }

  return { pluginName: alias, detectedAssets };
}

export interface UnbundleResult {
  marketplaceEmpty: boolean;
}

export function unbundlePlugin(workspacePath: string, alias: string): UnbundleResult {
  const wrapperDir = pluginWrapperDir(workspacePath, alias);
  if (existsSync(wrapperDir)) {
    rmSync(wrapperDir, { recursive: true, force: true });
  }
  const manifestPath = marketplaceManifestPath(workspacePath);
  if (!existsSync(manifestPath)) return { marketplaceEmpty: true };
  const manifest = readManifestOrEmpty(workspacePath);
  const next = removePluginFromManifest(manifest, alias);
  writeManifest(workspacePath, next);
  return { marketplaceEmpty: next.plugins.length === 0 };
}

interface MarketplaceListEntry {
  name?: string;
}

function isMarketplaceRegistered(workspacePath: string): boolean {
  try {
    const out = execFile("claude", ["plugin", "marketplace", "list", "--json"], workspacePath);
    const parsed = JSON.parse(out);
    const list: MarketplaceListEntry[] = Array.isArray(parsed)
      ? parsed
      : Array.isArray((parsed as { marketplaces?: unknown }).marketplaces)
        ? (parsed as { marketplaces: MarketplaceListEntry[] }).marketplaces
        : [];
    return list.some((m) => m?.name === WKT_MARKETPLACE_NAME);
  } catch {
    return false;
  }
}

export function registerMarketplaceIfMissing(workspacePath: string): void {
  if (isMarketplaceRegistered(workspacePath)) return;
  execFile(
    "claude",
    ["plugin", "marketplace", "add", `./.claude/marketplaces/${WKT_MARKETPLACE_NAME}`, "--scope", "project"],
    workspacePath,
  );
}

export function installPlugin(workspacePath: string, alias: string): void {
  execFile(
    "claude",
    ["plugin", "install", `${alias}@${WKT_MARKETPLACE_NAME}`, "--scope", "project"],
    workspacePath,
  );
}

export function uninstallPlugin(workspacePath: string, alias: string): void {
  execFile(
    "claude",
    ["plugin", "uninstall", `${alias}@${WKT_MARKETPLACE_NAME}`, "--scope", "project"],
    workspacePath,
  );
}

export function unregisterMarketplaceAndRemoveDir(workspacePath: string): void {
  try {
    execFile(
      "claude",
      ["plugin", "marketplace", "remove", WKT_MARKETPLACE_NAME, "--scope", "project"],
      workspacePath,
    );
  } catch {
    // Marketplace may already be gone (e.g. user removed it manually); still rm the dir below.
  }
  const dir = marketplaceDir(workspacePath);
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
  }
}
